### ISSUE TITLE
mongoCache should be in the package.json file ???

### ISSUE THREAD

**Issue by h18n** [lammertw/prerender-memjs-cache#3]
Error: Cannot find module './lib/mongoCache'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/haribabuviswanath/workspace/travelibibo/prerender/node_modules/prerender-memjs-cache/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by hooke** [comment]
This error is left on npm package, but fixed here with 2b5bf40 commit. Since npm package is not updated up to now, you can install directly from github using 
`npm install lammertw/prerender-memjs-cache --save`
